# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ariez/Work/mpicomm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ariez/Work/mpicomm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariez/Work/mpicomm/CMakeFiles /home/ariez/Work/mpicomm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariez/Work/mpicomm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test_lib

# Build rule for target.
test_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_lib
.PHONY : test_lib

# fast build rule for target.
test_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/build
.PHONY : test_lib/fast

#=============================================================================
# Target rules for targets named test_index

# Build rule for target.
test_index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_index
.PHONY : test_index

# fast build rule for target.
test_index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/build
.PHONY : test_index/fast

#=============================================================================
# Target rules for targets named test_graph

# Build rule for target.
test_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_graph
.PHONY : test_graph

# fast build rule for target.
test_graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/build
.PHONY : test_graph/fast

#=============================================================================
# Target rules for targets named mpicomm

# Build rule for target.
mpicomm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpicomm
.PHONY : mpicomm

# fast build rule for target.
mpicomm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/build
.PHONY : mpicomm/fast

graph.o: graph.c.o
.PHONY : graph.o

# target to build an object file
graph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/graph.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/graph.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/graph.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/graph.c.o
.PHONY : graph.c.o

graph.i: graph.c.i
.PHONY : graph.i

# target to preprocess a source file
graph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/graph.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/graph.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/graph.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/graph.c.i
.PHONY : graph.c.i

graph.s: graph.c.s
.PHONY : graph.s

# target to generate assembly for a file
graph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/graph.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/graph.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/graph.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/graph.c.s
.PHONY : graph.c.s

index.o: index.c.o
.PHONY : index.o

# target to build an object file
index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/index.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/index.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/index.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/index.c.o
.PHONY : index.c.o

index.i: index.c.i
.PHONY : index.i

# target to preprocess a source file
index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/index.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/index.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/index.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/index.c.i
.PHONY : index.c.i

index.s: index.c.s
.PHONY : index.s

# target to generate assembly for a file
index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/index.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/index.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/index.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/index.c.s
.PHONY : index.c.s

lib.o: lib.c.o
.PHONY : lib.o

# target to build an object file
lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/lib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/lib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/lib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/lib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/lib.c.o
.PHONY : lib.c.o

lib.i: lib.c.i
.PHONY : lib.i

# target to preprocess a source file
lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/lib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/lib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/lib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/lib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/lib.c.i
.PHONY : lib.c.i

lib.s: lib.c.s
.PHONY : lib.s

# target to generate assembly for a file
lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/lib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/lib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/lib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/lib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/lib.c.s
.PHONY : lib.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpicomm.dir/build.make CMakeFiles/mpicomm.dir/main.c.s
.PHONY : main.c.s

test/test_graph.o: test/test_graph.c.o
.PHONY : test/test_graph.o

# target to build an object file
test/test_graph.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test/test_graph.c.o
.PHONY : test/test_graph.c.o

test/test_graph.i: test/test_graph.c.i
.PHONY : test/test_graph.i

# target to preprocess a source file
test/test_graph.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test/test_graph.c.i
.PHONY : test/test_graph.c.i

test/test_graph.s: test/test_graph.c.s
.PHONY : test/test_graph.s

# target to generate assembly for a file
test/test_graph.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test/test_graph.c.s
.PHONY : test/test_graph.c.s

test/test_index.o: test/test_index.c.o
.PHONY : test/test_index.o

# target to build an object file
test/test_index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test/test_index.c.o
.PHONY : test/test_index.c.o

test/test_index.i: test/test_index.c.i
.PHONY : test/test_index.i

# target to preprocess a source file
test/test_index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test/test_index.c.i
.PHONY : test/test_index.c.i

test/test_index.s: test/test_index.c.s
.PHONY : test/test_index.s

# target to generate assembly for a file
test/test_index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test/test_index.c.s
.PHONY : test/test_index.c.s

test/test_lib.o: test/test_lib.c.o
.PHONY : test/test_lib.o

# target to build an object file
test/test_lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/test/test_lib.c.o
.PHONY : test/test_lib.c.o

test/test_lib.i: test/test_lib.c.i
.PHONY : test/test_lib.i

# target to preprocess a source file
test/test_lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/test/test_lib.c.i
.PHONY : test/test_lib.c.i

test/test_lib.s: test/test_lib.c.s
.PHONY : test/test_lib.s

# target to generate assembly for a file
test/test_lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/test/test_lib.c.s
.PHONY : test/test_lib.c.s

test/test_main.o: test/test_main.c.o
.PHONY : test/test_main.o

# target to build an object file
test/test_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/test_main.c.o
.PHONY : test/test_main.c.o

test/test_main.i: test/test_main.c.i
.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/test_main.c.i
.PHONY : test/test_main.c.i

test/test_main.s: test/test_main.c.s
.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/test_main.c.s
.PHONY : test/test_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mpicomm"
	@echo "... test_graph"
	@echo "... test_index"
	@echo "... test_lib"
	@echo "... test_main"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... index.o"
	@echo "... index.i"
	@echo "... index.s"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test/test_graph.o"
	@echo "... test/test_graph.i"
	@echo "... test/test_graph.s"
	@echo "... test/test_index.o"
	@echo "... test/test_index.i"
	@echo "... test/test_index.s"
	@echo "... test/test_lib.o"
	@echo "... test/test_lib.i"
	@echo "... test/test_lib.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

